#---------------------------------#
#   master branch configuration   #
#---------------------------------#
-
  branches:
    only:
      - master

  environment:
    # Set your VSTS Personal Access Token to facilitate publishing
    # Don't store it in the clear, encrypt it: https://ci.appveyor.com/tools/encrypt
    VSTS_PAT:
      secure: H/UHOP7KVeCcaTkvMe7cp9pn8RlCdvQUOUajO0urYVaL8rr2VbLA+/oJTd+0nRvngg5ZJxwexPLdAKc2oxaxtQ==

  install:
    # Install the TFX Command Line Interface
    npm i -g tfx-cli

  before_build:
    - ps: .\SyncPSModules.ps1

  # publish privately by default. override to public: true if merging to master
  build_script:
    IF "%APPVEYOR_PULL_REQUEST_NUMBER%"=="" (
      tfx extension publish --manifest-globs vss-extension.json --auth-type 'pat' --token %VSTS_PAT% --override "{\"version\":\"%APPVEYOR_BUILD_VERSION%\"}"
    ) ELSE (
      tfx extension publish --manifest-globs vss-extension.json --auth-type 'pat' --token %VSTS_PAT% --override "{\"public\":true,\"version\":\"%APPVEYOR_BUILD_VERSION%\"}"
    )

  artifacts:
    - path: ./*.vsix
      name: vsts-f5-tasks