environment:
  # Set your VSTS Personal Access Token to facilitate publishing
  # Don't store it in the clear, encrypt it: https://ci.appveyor.com/tools/encrypt
  VSTS_PAT:
    secure: iqUYqYl3XnwCRgz/d73lDL3g2xZCrq9HK3Rzspz7BLqQPcJ80opbDm0PrHQTt8nDfLP1wpQNaQxrmobRb3SD+Q==

install:
  # Install the TFX Command Line Interface
  npm i -g tfx-cli

before_build:
  - ps: .\SyncCommon.ps1

build_script:
  tfx extension publish --manifest-globs vss-extension.json --auth-type 'pat' --token %VSTS_PAT% --override "{\"version\":\"%APPVEYOR_BUILD_VERSION%\"}"

artifacts:
  - path: ./*.vsix
    name: vsts-f5-tasks